### ISSUE TITLE
Mod not working from Unciv 1.13.13 and later

### ISSUE THREAD

**Issue by shannaurelle** [Cavenir/Extra-Resources#5]
I have problems, also others with including the mod on its own. It might be caused by the logic of the bug fixer in yairm's code. I have searched for possible reasons in the code why the error appears
1. Some unit reference a tech that is not part of the ruleset
2. The building tech is not defined (it may be that the tech isn't present in the ruleset) and the cost of the building is zero
3. The unit upgrades to itself (idk how this happens though, havent tried)

**Comment by Cavenir** [comment]
Let me try to analyze and fix the code first, then I will let you know if there is anything else.
